file_format: "1"
id: reviung41oled
name: REVIUNG41OLED
type: shield
url: https://github.com/gtips/reviung/tree/master/reviung41
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
